"""Chat with the assistant.

Single shared thread, persisted in SQLite, profile-tagged. The reply is
generated by an OpenAI-compatible endpoint when ``OPENAI_API_KEY`` is set,
otherwise a friendly offline reply is returned -- the UI keeps working
end-to-end without any external dependency.
"""

from __future__ import annotations

from datetime import datetime

import httpx
from fastapi import APIRouter, Depends, HTTPException, status

from ..config import Settings, get_settings
from ..db import get_connection, log_activity
from ..deps import current_profile_key, require_session
from ..models import ChatMessage, ChatSendRequest, ChatSendResponse, ChatStatus

router = APIRouter(prefix="/chat", tags=["chat"], dependencies=[Depends(require_session)])

HISTORY_LIMIT = 200
LLM_CONTEXT_TURNS = 16
LLM_TIMEOUT_SECONDS = 30
OFFLINE_REPLY = (
    "I'm offline right now -- no LLM key is configured. Set OPENAI_API_KEY in "
    ".env (any OpenAI-compatible endpoint works) and restart the backend, then "
    "I can reply for real. Your messages are still being saved here."
)
SYSTEM_PROMPT = (
    "You are {name}, the AI assistant inside Openclaw -- an internal command "
    "center for two operators (Daniel and his business partner). Be concise, "
    "warm, and direct. The current user is {speaker}. When asked about the "
    "businesses, prefer JobCarver-related context. Don't invent data; if you "
    "need a fact, ask. Format short answers as plain text, longer ones with "
    "headings/bullets where it helps."
)


def _row_to_message(row, profile_name: str | None = None) -> ChatMessage:
    return ChatMessage(
        id=row["id"],
        role=row["role"],
        content=row["content"],
        profile_key=row["profile_key"],
        profile_name=profile_name,
        created_at=datetime.fromisoformat(row["created_at"]),
    )


def _profile_name_for(key: str | None) -> str | None:
    if not key:
        return None
    conn = get_connection()
    row = conn.execute("SELECT name FROM profiles WHERE key = ?", (key,)).fetchone()
    return row["name"] if row else None


def _insert_message(role: str, content: str, profile_key: str | None) -> ChatMessage:
    conn = get_connection()
    cur = conn.execute(
        "INSERT INTO chat_messages (role, content, profile_key) VALUES (?, ?, ?)",
        (role, content, profile_key),
    )
    row = conn.execute(
        "SELECT * FROM chat_messages WHERE id = ?", (cur.lastrowid,)
    ).fetchone()
    return _row_to_message(row, _profile_name_for(profile_key))


async def _llm_reply(history: list[dict[str, str]], settings: Settings) -> str:
    """Call an OpenAI-compatible /chat/completions endpoint."""
    headers = {
        "Authorization": f"Bearer {settings.openai_api_key}",
        "Content-Type": "application/json",
    }
    body = {
        "model": settings.openai_model,
        "messages": history,
        "temperature": 0.4,
    }
    url = settings.openai_base_url.rstrip("/") + "/chat/completions"
    async with httpx.AsyncClient(timeout=LLM_TIMEOUT_SECONDS) as client:
        resp = await client.post(url, headers=headers, json=body)
        resp.raise_for_status()
        data = resp.json()
    try:
        return data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError, TypeError) as exc:
        raise RuntimeError("unexpected LLM response shape") from exc


@router.get("/status", response_model=ChatStatus)
def status_endpoint(settings: Settings = Depends(get_settings)) -> ChatStatus:
    online = bool(settings.openai_api_key)
    return ChatStatus(
        online=online,
        model=settings.openai_model if online else None,
        assistant_name=settings.assistant_name,
    )


@router.get("/messages", response_model=list[ChatMessage])
def list_messages() -> list[ChatMessage]:
    conn = get_connection()
    rows = conn.execute(
        "SELECT m.*, p.name AS profile_name FROM chat_messages m "
        "LEFT JOIN profiles p ON p.key = m.profile_key "
        "ORDER BY m.created_at ASC, m.id ASC LIMIT ?",
        (HISTORY_LIMIT,),
    ).fetchall()
    return [
        ChatMessage(
            id=r["id"],
            role=r["role"],
            content=r["content"],
            profile_key=r["profile_key"],
            profile_name=r["profile_name"],
            created_at=datetime.fromisoformat(r["created_at"]),
        )
        for r in rows
    ]


@router.post(
    "/messages", response_model=ChatSendResponse, status_code=status.HTTP_201_CREATED
)
async def send_message(
    body: ChatSendRequest,
    profile_key: str | None = Depends(current_profile_key),
    settings: Settings = Depends(get_settings),
) -> ChatSendResponse:
    content = body.content.strip()
    if not content:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "empty message")

    user_msg = _insert_message("user", content, profile_key)
    log_activity("chat.send", "Asked Mia a question", profile_key=profile_key)

    online = bool(settings.openai_api_key)
    if not online:
        reply_text = OFFLINE_REPLY
    else:
        speaker = _profile_name_for(profile_key) or "an operator"
        sys_msg = {
            "role": "system",
            "content": SYSTEM_PROMPT.format(name=settings.assistant_name, speaker=speaker),
        }
        # Pull the last N turns for context (cheap; trims unbounded history).
        conn = get_connection()
        rows = conn.execute(
            "SELECT role, content FROM chat_messages ORDER BY id DESC LIMIT ?",
            (LLM_CONTEXT_TURNS,),
        ).fetchall()
        recent = [{"role": r["role"], "content": r["content"]} for r in reversed(rows)]
        history = [sys_msg, *recent]
        try:
            reply_text = await _llm_reply(history, settings)
        except (httpx.HTTPError, RuntimeError):
            # Don't leak provider error details to the client.
            reply_text = (
                "I couldn't reach the LLM just now. Your message is saved -- "
                "try again in a moment, or check the backend logs for the "
                "provider error."
            )
            online = False

    reply_msg = _insert_message("assistant", reply_text, None)
    return ChatSendResponse(user=user_msg, reply=reply_msg, online=online)


@router.delete("/messages", status_code=status.HTTP_204_NO_CONTENT)
def clear_messages(profile_key: str | None = Depends(current_profile_key)) -> None:
    conn = get_connection()
    conn.execute("DELETE FROM chat_messages")
    log_activity("chat.clear", "Cleared the chat history", profile_key=profile_key)
